### ISSUE TITLE
working with circular grids

### ISSUE THREAD

**Issue by lotruheawea** [Deltares/pyflwdir#43]
Dear dev team,
first of all, thank you very much for your great work. 
I would like to request the feature to be able to set up a FlwdirRaster that has a circular raster referenced. I apply your tools on a global grid defined in a lat-lon grid with lon ranging from -180 to 180 deg. The discontinuity at the boundary causes basins to be split. It would be great to have a way of defining the grid so that the longitutes are angular.
Thanks!

**Comment by DirkEilander** [comment]
Thanks for you feature request @lotruheawea. 

This is not our planning to include any time soon, but I'd be happy to discuss possibilities if you're keen to implement it. 

I've had the same issue in the past and then circumvented it by shifting the grid for basins that cross the 180 degree meridian: i.e., shift all cells west of 0 deg longitude by 360 degrees east so that you obtain a 0-360 degree grid.

**Comment by DirkEilander** [comment]
close this issue as it has been stale for a long time
